name: yc_flutter_utils
description: flutter utils
version: 0.0.4
homepage: https://github.com/yangchong211/YCFlutterUtils


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^0.3.5
  async: ^2.4.2
  crypto: ^2.1.5
  convert: ^2.1.1
  http: ^0.11.3+12
  path_provider: ^1.6.9
  provider: 4.0.0
  cached_network_image: ^2.0.0
  shared_preferences: ^0.5.6
  dio: 3.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.utils.yc_flutter_utils
        pluginClass: YcFlutterUtilsPlugin
      ios:
        pluginClass: YcFlutterUtilsPlugin
